files: [./challenge/05.mat]
#dirs: [./data/dicom1, ./data/dicom2]
outDir: ./out
reScale: 0.0001 # Rescaling might be needed for datasets with too small/large pixel values
sliceList: [0, 1, 2, 3]
echoes: [0, 1, 2]
temperature: 37
crop: [64, 64, 0, 128, 92, 4] # [x0, y0, z0, x1, y1, z1]
clockwisePrecession: False
offresCenter: 0.